### ISSUE TITLE
Filtering in All Upcoming Coding Competitions Page

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/Algorithmist#19] opened 2022-11-21 20:49 UTC
There are tags on the page that are dummies, now our task is to show those competitions whose tags are selected. By default the _all tag_ is selected and we show all competitions. 

<img width="1025" alt="Screenshot 2022-11-22 at 2 15 15 AM" src="https://user-images.githubusercontent.com/93304796/203154865-84f19c30-3b1f-4002-9e4a-e98c8014a3bb.png">
<br/><br/>
**Few resources that might help : ** <br/>
- Tags are coming from the backend in form of an array 
<img width="629" alt="Screenshot 2022-11-22 at 2 16 35 AM" src="https://user-images.githubusercontent.com/93304796/203155068-669e3805-f7c9-44af-814a-eaaa0850240a.png">

- Sheet from where we are pulling the data : https://docs.google.com/spreadsheets/d/1-cTddH1wJRtyKazJuAWHdzK8Wjp1hwf36l3kONy6tE0/edit#gid=0

- Google sheets API (data already fetched on page): https://script.google.com/macros/s/AKfycbzXyVH1o6CzzJUfLN0qC-EscTKQeKouAUlU3oBs_S85WvB13wPHuawZLK43QJrqBua3Ng/exec

**Comment by jinitsuga** [comment] 2022-11-22 23:45
I can probably take care of this :)

**Comment by Nayaker** [comment] 2022-11-23 04:46
Amazing, I will assign this task to you then. @jinitsuga in case you want to add some more dummy data in the  <a href="https://docs.google.com/spreadsheets/d/1-cTddH1wJRtyKazJuAWHdzK8Wjp1hwf36l3kONy6tE0/edit#gid=0" target="_blank">google sheet</a> for testing consider sharing your email id, I will add you as an editor of the sheet.

**Comment by jinitsuga** [comment] 2022-11-25 00:28
I see my PR was merged but the issue is still open, I think I forgot to link the PR to this issue.

**Comment by Nayaker** [comment] 2022-11-25 00:42
@jinitsuga Great stuff man, no problem I will close the issue. I was reading the code and changing a couple of things here and there, that is why didn't close the issue. 

- Just read the whole code, very nice and clean way of writing code @jinitsuga. Amazing man, I have also added your github link on the landing page.

- Also thanks for telling me about the UI crash error message, I just resolved it.
 
- I have changed the file structure you did a bit, for a better future understanding of the code like moving the CompetitionItem.js from Screen to Components.

- Right now I don't have any issue in mind, but if there is some issue or enhancement that you think exists you can add it to the issues section and work on it.

**Closed** 2022-11-25 00:42 UTC
Labels: enhancement, good first issue
